### ISSUE TITLE
Couldn't handle packet of type CHANNEL_CREATE

### ISSUE THREAD

**Issue by titivermeesch** [Javacord/Javacord#483]
Hello there,

So I'm pretty new with Javacord so it's possible that I'm doing this completely wrong, but I try to create a channel like this : 
`Iterator<Server> iterator = api.getServers().iterator();
        new ServerVoiceChannelBuilder(iterator.next())
                .setName("PlayBossWar")
                .setUserlimit(10)
                .create();`

This is the error I get : 

`[21:30:48] [Javacord - Handlers Processor/WARN]: Couldn't handle packet of type PRESENCE_UPDATE. Please contact the developer! (packet: {"user":{"id":"514328208141844481"},"status":"online","roles":[],"guild_id":"439618742633103370","game":{"type":0,"timestamps":{"start":1561231680000},"state":"Menu principal","party":{},"name":"Paladins","id":"43e169631115d7b","created_at":1561231847961,"assets":{"large_image":"528327528230944769"},"application_id":"528145079819436043"},"client_status":{"desktop":"online"},"activities":[{"type":0,"timestamps":{"start":1561231680000},"state":"Menu principal","party":{},"name":"Paladins","id":"43e169631115d7b","created_at":1561231847961,"assets":{"large_image":"528327528230944769"},"application_id":"528145079819436043"}]})
java.lang.NoClassDefFoundError: org/javacord/core/entity/activity/ActivityPartyImpl
	at org.javacord.core.entity.activity.ActivityImpl.<init>(ActivityImpl.java:40) ~[?:?]
	at org.javacord.core.util.handler.user.PresenceUpdateHandler.lambda$handle$0(PresenceUpdateHandler.java:51) ~[?:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at org.javacord.core.util.handler.user.PresenceUpdateHandler.handle(PresenceUpdateHandler.java:47) ~[?:?]
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]`

**Comment by Vampire** [comment]
Is this really the first error you get? `NoClassDefFoundError ` is usually not the first error and not the real cause.

Also, do you use the latest version of Javacord?

**Comment by titivermeesch** [comment]
Yes it's the first and only one. I use the latest version that I got from maven

**Comment by Vampire** [comment]
So 3.0.4?
Do you use the artifacts how we provide them, or do you follow bad practices like building a fat jar? 
If the latter, is the class it misses present in your jar? 
And if so, try using the jars we provide unmodified.

**Comment by titivermeesch** [comment]
Yes I use 3.0.4.
I added the depencency with maven and then installed it, used the snapshot jar that came from that

**Comment by titivermeesch** [comment]
Ok so for some reasons it works great if I try the examples out, but It's confusing me with the fact that I have to retrieve the server, is that the way to do it? It's not very clear on the wiki

**Comment by titivermeesch** [comment]
Ok well it seems like it works now
